name: esp32_comm_example
description: An example project for esp32_comm package.
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  esp32_comm:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
